-- Migrazione trasporto_arrivo/partenza da testo libero a JSON strutturato
-- { mezzo, mezzo_altro, dettagli, lat, lng, link }

UPDATE tappe SET trasporto_arrivo = '{"mezzo": "aereo", "mezzo_altro": "", "dettagli": "Volo HU0492 BRU → PEK · arrivo 22 ago 05:00", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Pechino Nord → Datong Sud · 07:30 · 25 agosto", "lat": null, "lng": null, "link": ""}' WHERE id = 101;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Pechino Nord → Datong Sud · 07:30 · 25 agosto", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Datong Sud → Xi''an · 06:58 · 26 agosto", "lat": null, "lng": null, "link": ""}' WHERE id = 102;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Datong Sud → Xi''an · 06:58 · 26 agosto", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Xi''an → Changsha · sera 28 agosto · ~5h", "lat": null, "lng": null, "link": ""}' WHERE id = 103;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Xi''an → Changsha · ~5h · sera 28 agosto", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Changsha South → Zhangjiajie West · ~2h · mattina 29 agosto", "lat": null, "lng": null, "link": ""}' WHERE id = 104;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Changsha → Zhangjiajie West · ~2h · 29 agosto", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Zhangjiajie → Fenghuanggucheng · poi taxi 10 km · 31 agosto", "lat": null, "lng": null, "link": ""}' WHERE id = 105;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "AV Zhangjiajie → Fenghuanggucheng ~1h · 31 agosto", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "Treno Fenghuanggucheng → Guilin · ~3-4h · 1 settembre", "lat": null, "lng": null, "link": ""}' WHERE id = 106;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "Treno Fenghuanggucheng → Guilin · ~3-4h · 1 settembre", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "nave", "mezzo_altro": "", "dettagli": "Crociera Li River → Yangshuo · 3 settembre · poi → Hong Kong · 4 settembre", "lat": null, "lng": null, "link": ""}' WHERE id = 107;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "nave", "mezzo_altro": "", "dettagli": "Crociera Li River → Yangshuo · 3 settembre", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "altro", "mezzo_altro": "auto + treno AV + metro", "dettagli": "Yangshuo → Guilin → Guangzhou AV (~2h30) → MTR Hong Kong (~50 min) · 4 settembre", "lat": null, "lng": null, "link": ""}' WHERE id = 108;
UPDATE tappe SET trasporto_arrivo = '{"mezzo": "treno", "mezzo_altro": "", "dettagli": "MTR Cross-Boundary Guangzhou → West Kowloon · ~50 min · 4 settembre", "lat": null, "lng": null, "link": ""}', trasporto_partenza = '{"mezzo": "aereo", "mezzo_altro": "", "dettagli": "Volo VN0593 HKG → HAN 14:30 · scalo 9h15 · VN0073 00:50 → MXP · PNR XLGNLT", "lat": null, "lng": null, "link": ""}' WHERE id = 109;
UPDATE tappe SET trasporto_arrivo = NULL, trasporto_partenza = NULL WHERE id = 201;