-- Catalogo condiviso Wandex: province italiane, capitali europee, capitali del mondo.
-- Non ha utente_id: è lo stesso elenco per tutti gli utenti; chi ha visitato cosa
-- resta in wandex_voci (quella sì per-utente).
CREATE TABLE IF NOT EXISTS wandex_catalogo (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  categoria TEXT NOT NULL,
  chiave    TEXT NOT NULL,
  nome      TEXT NOT NULL,
  gruppo    TEXT,
  paese     TEXT,
  iso       TEXT,
  lat       REAL,
  lng       REAL,
  UNIQUE(categoria, chiave)
);

INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AQ', 'L''Aquila', 'Abruzzo', NULL, 'IT', 42.3498, 13.3995);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CH', 'Chieti', 'Abruzzo', NULL, 'IT', 42.3505, 14.1679);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PE', 'Pescara', 'Abruzzo', NULL, 'IT', 42.4617, 14.2153);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TE', 'Teramo', 'Abruzzo', NULL, 'IT', 42.6589, 13.704);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MT', 'Matera', 'Basilicata', NULL, 'IT', 40.6664, 16.6043);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PZ', 'Potenza', 'Basilicata', NULL, 'IT', 40.6404, 15.8056);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CZ', 'Catanzaro', 'Calabria', NULL, 'IT', 38.9097, 16.5878);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CS', 'Cosenza', 'Calabria', NULL, 'IT', 39.3007, 16.2536);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'KR', 'Crotone', 'Calabria', NULL, 'IT', 39.0852, 17.1286);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RC', 'Reggio Calabria', 'Calabria', NULL, 'IT', 38.1143, 15.6487);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VV', 'Vibo Valentia', 'Calabria', NULL, 'IT', 38.6762, 16.0997);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AV', 'Avellino', 'Campania', NULL, 'IT', 40.9143, 14.7908);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BN', 'Benevento', 'Campania', NULL, 'IT', 41.1297, 14.7827);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CE', 'Caserta', 'Campania', NULL, 'IT', 41.074, 14.3328);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'NA', 'Napoli', 'Campania', NULL, 'IT', 40.8518, 14.2681);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SA', 'Salerno', 'Campania', NULL, 'IT', 40.6824, 14.7681);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BO', 'Bologna', 'Emilia-Romagna', NULL, 'IT', 44.4949, 11.3426);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'FE', 'Ferrara', 'Emilia-Romagna', NULL, 'IT', 44.8381, 11.6198);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'FC', 'Forlì-Cesena', 'Emilia-Romagna', NULL, 'IT', 44.2227, 12.0408);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MO', 'Modena', 'Emilia-Romagna', NULL, 'IT', 44.6471, 10.9252);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PR', 'Parma', 'Emilia-Romagna', NULL, 'IT', 44.8015, 10.3279);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PC', 'Piacenza', 'Emilia-Romagna', NULL, 'IT', 45.0526, 9.6934);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RA', 'Ravenna', 'Emilia-Romagna', NULL, 'IT', 44.4184, 12.2035);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RN', 'Rimini', 'Emilia-Romagna', NULL, 'IT', 44.0678, 12.5695);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RE', 'Reggio Emilia', 'Emilia-Romagna', NULL, 'IT', 44.6989, 10.6297);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'GO', 'Gorizia', 'Friuli-Venezia Giulia', NULL, 'IT', 45.9403, 13.6217);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PN', 'Pordenone', 'Friuli-Venezia Giulia', NULL, 'IT', 45.9561, 12.6612);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TS', 'Trieste', 'Friuli-Venezia Giulia', NULL, 'IT', 45.6495, 13.7768);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'UD', 'Udine', 'Friuli-Venezia Giulia', NULL, 'IT', 46.0711, 13.235);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'FR', 'Frosinone', 'Lazio', NULL, 'IT', 41.639, 13.3395);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'LT', 'Latina', 'Lazio', NULL, 'IT', 41.4677, 12.9036);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RI', 'Rieti', 'Lazio', NULL, 'IT', 42.4044, 12.8628);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RM', 'Roma', 'Lazio', NULL, 'IT', 41.9028, 12.4964);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VT', 'Viterbo', 'Lazio', NULL, 'IT', 42.4171, 12.1065);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'GE', 'Genova', 'Liguria', NULL, 'IT', 44.4056, 8.9463);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'IM', 'Imperia', 'Liguria', NULL, 'IT', 43.8923, 8.0307);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SP', 'La Spezia', 'Liguria', NULL, 'IT', 44.1077, 9.8227);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SV', 'Savona', 'Liguria', NULL, 'IT', 44.3077, 8.4822);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BG', 'Bergamo', 'Lombardia', NULL, 'IT', 45.6983, 9.6773);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BS', 'Brescia', 'Lombardia', NULL, 'IT', 45.5416, 10.2118);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CO', 'Como', 'Lombardia', NULL, 'IT', 45.8081, 9.0852);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CR', 'Cremona', 'Lombardia', NULL, 'IT', 45.1349, 10.0218);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'LC', 'Lecco', 'Lombardia', NULL, 'IT', 45.8566, 9.3904);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'LO', 'Lodi', 'Lombardia', NULL, 'IT', 45.3147, 9.5037);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MN', 'Mantova', 'Lombardia', NULL, 'IT', 45.1564, 10.7914);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MI', 'Milano', 'Lombardia', NULL, 'IT', 45.4654, 9.1859);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MB', 'Monza-Brianza', 'Lombardia', NULL, 'IT', 45.5845, 9.2744);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PV', 'Pavia', 'Lombardia', NULL, 'IT', 45.1847, 9.1582);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SO', 'Sondrio', 'Lombardia', NULL, 'IT', 46.1697, 9.8703);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VA', 'Varese', 'Lombardia', NULL, 'IT', 45.8206, 8.8257);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AN', 'Ancona', 'Marche', NULL, 'IT', 43.6158, 13.5189);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AP', 'Ascoli Piceno', 'Marche', NULL, 'IT', 42.8637, 13.5795);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'FM', 'Fermo', 'Marche', NULL, 'IT', 43.1601, 13.7229);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MC', 'Macerata', 'Marche', NULL, 'IT', 43.2998, 13.4533);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PU', 'Pesaro-Urbino', 'Marche', NULL, 'IT', 43.873, 12.9135);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CB', 'Campobasso', 'Molise', NULL, 'IT', 41.5606, 14.6637);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'IS', 'Isernia', 'Molise', NULL, 'IT', 41.5925, 14.2307);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AL', 'Alessandria', 'Piemonte', NULL, 'IT', 44.9136, 8.615);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AT', 'Asti', 'Piemonte', NULL, 'IT', 44.9003, 8.2064);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BI', 'Biella', 'Piemonte', NULL, 'IT', 45.5624, 8.0585);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CN', 'Cuneo', 'Piemonte', NULL, 'IT', 44.3844, 7.5425);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'NO', 'Novara', 'Piemonte', NULL, 'IT', 45.4455, 8.6219);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TO', 'Torino', 'Piemonte', NULL, 'IT', 45.0703, 7.6869);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VB', 'Verbano-Cusio-Ossola', 'Piemonte', NULL, 'IT', 45.9291, 8.5766);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VC', 'Vercelli', 'Piemonte', NULL, 'IT', 45.3206, 8.4181);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BA', 'Bari', 'Puglia', NULL, 'IT', 41.1171, 16.8719);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BT', 'Barletta-Andria-Trani', 'Puglia', NULL, 'IT', 41.2003, 16.2948);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BR', 'Brindisi', 'Puglia', NULL, 'IT', 40.6328, 17.9409);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'FG', 'Foggia', 'Puglia', NULL, 'IT', 41.4621, 15.5446);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'LE', 'Lecce', 'Puglia', NULL, 'IT', 40.352, 18.1742);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TA', 'Taranto', 'Puglia', NULL, 'IT', 40.4644, 17.247);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CA', 'Cagliari', 'Sardegna', NULL, 'IT', 39.2238, 9.1217);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CI', 'Carbonia-Iglesias', 'Sardegna', NULL, 'IT', 39.1668, 8.5329);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VS', 'Medio Campidano', 'Sardegna', NULL, 'IT', 39.5298, 8.7362);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'NU', 'Nuoro', 'Sardegna', NULL, 'IT', 40.3214, 9.3268);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'OG', 'Ogliastra', 'Sardegna', NULL, 'IT', 39.688, 9.5039);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'OT', 'Olbia-Tempio', 'Sardegna', NULL, 'IT', 40.9237, 9.4992);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'OR', 'Oristano', 'Sardegna', NULL, 'IT', 39.906, 8.5917);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SS', 'Sassari', 'Sardegna', NULL, 'IT', 40.7259, 8.5555);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AG', 'Agrigento', 'Sicilia', NULL, 'IT', 37.3111, 13.5765);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CL', 'Caltanissetta', 'Sicilia', NULL, 'IT', 37.4908, 14.0632);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'CT', 'Catania', 'Sicilia', NULL, 'IT', 37.5079, 15.083);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'EN', 'Enna', 'Sicilia', NULL, 'IT', 37.5667, 14.277);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'ME', 'Messina', 'Sicilia', NULL, 'IT', 38.1938, 15.554);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PA', 'Palermo', 'Sicilia', NULL, 'IT', 38.1157, 13.3615);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RG', 'Ragusa', 'Sicilia', NULL, 'IT', 36.9268, 14.7276);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SR', 'Siracusa', 'Sicilia', NULL, 'IT', 37.0755, 15.2866);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TP', 'Trapani', 'Sicilia', NULL, 'IT', 37.9992, 12.5363);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AR', 'Arezzo', 'Toscana', NULL, 'IT', 43.4633, 11.8796);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'FI', 'Firenze', 'Toscana', NULL, 'IT', 43.7696, 11.2558);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'GR', 'Grosseto', 'Toscana', NULL, 'IT', 42.7637, 11.1117);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'LI', 'Livorno', 'Toscana', NULL, 'IT', 43.5485, 10.3106);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'LU', 'Lucca', 'Toscana', NULL, 'IT', 43.843, 10.5074);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'MS', 'Massa-Carrara', 'Toscana', NULL, 'IT', 44.0318, 10.1429);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PI', 'Pisa', 'Toscana', NULL, 'IT', 43.7228, 10.4017);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PT', 'Pistoia', 'Toscana', NULL, 'IT', 43.93, 10.9175);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PO', 'Prato', 'Toscana', NULL, 'IT', 43.8777, 11.1023);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'SI', 'Siena', 'Toscana', NULL, 'IT', 43.3186, 11.3307);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BZ', 'Bolzano', 'Trentino-Alto Adige', NULL, 'IT', 46.4983, 11.3548);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TN', 'Trento', 'Trentino-Alto Adige', NULL, 'IT', 46.0664, 11.1257);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PG', 'Perugia', 'Umbria', NULL, 'IT', 43.1107, 12.3908);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TR', 'Terni', 'Umbria', NULL, 'IT', 42.5636, 12.643);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'AO', 'Aosta', 'Valle d''Aosta', NULL, 'IT', 45.7372, 7.3202);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'BL', 'Belluno', 'Veneto', NULL, 'IT', 46.1411, 12.2159);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'PD', 'Padova', 'Veneto', NULL, 'IT', 45.4064, 11.8768);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'RO', 'Rovigo', 'Veneto', NULL, 'IT', 45.0714, 11.7906);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'TV', 'Treviso', 'Veneto', NULL, 'IT', 45.6669, 12.243);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VE', 'Venezia', 'Veneto', NULL, 'IT', 45.4408, 12.3155);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VR', 'Verona', 'Veneto', NULL, 'IT', 45.4386, 10.9916);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('province', 'VI', 'Vicenza', 'Veneto', NULL, 'IT', 45.5455, 11.5354);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Amsterdam', 'Amsterdam', NULL, 'Paesi Bassi', 'NL', 52.3676, 4.9041);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Andorra la Vella', 'Andorra la Vella', NULL, 'Andorra', 'AD', 42.5063, 1.5218);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Atene', 'Atene', NULL, 'Grecia', 'GR', 37.9838, 23.7275);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Baku', 'Baku', NULL, 'Azerbaigian', 'AZ', 40.4093, 49.8671);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Belgrado', 'Belgrado', NULL, 'Serbia', 'RS', 44.8176, 20.4569);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Berlino', 'Berlino', NULL, 'Germania', 'DE', 52.52, 13.405);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Berna', 'Berna', NULL, 'Svizzera', 'CH', 46.948, 7.4474);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Bratislava', 'Bratislava', NULL, 'Slovacchia', 'SK', 48.1486, 17.1077);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Bruxelles', 'Bruxelles', NULL, 'Belgio', 'BE', 50.8503, 4.3517);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Bucarest', 'Bucarest', NULL, 'Romania', 'RO', 44.4268, 26.1025);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Budapest', 'Budapest', NULL, 'Ungheria', 'HU', 47.4979, 19.0402);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Chisinau', 'Chisinau', NULL, 'Moldova', 'MD', 47.0105, 28.8638);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Copenaghen', 'Copenaghen', NULL, 'Danimarca', 'DK', 55.6761, 12.5683);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Dublino', 'Dublino', NULL, 'Irlanda', 'IE', 53.3498, -6.2603);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Helsinki', 'Helsinki', NULL, 'Finlandia', 'FI', 60.1699, 24.9384);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Kiev', 'Kiev', NULL, 'Ucraina', 'UA', 50.4501, 30.5234);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Lisbona', 'Lisbona', NULL, 'Portogallo', 'PT', 38.7223, -9.1393);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Lubiana', 'Lubiana', NULL, 'Slovenia', 'SI', 46.0569, 14.5058);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Lussemburgo', 'Lussemburgo', NULL, 'Lussemburgo', 'LU', 49.6116, 6.1319);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Madrid', 'Madrid', NULL, 'Spagna', 'ES', 40.4168, -3.7038);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Minsk', 'Minsk', NULL, 'Bielorussia', 'BY', 53.9045, 27.5615);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Monaco', 'Monaco', NULL, 'Monaco', 'MC', 43.7384, 7.4246);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Mosca', 'Mosca', NULL, 'Russia', 'RU', 55.7558, 37.6173);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Nicosia', 'Nicosia', NULL, 'Cipro', 'CY', 35.1856, 33.3823);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Oslo', 'Oslo', NULL, 'Norvegia', 'NO', 59.9139, 10.7522);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Parigi', 'Parigi', NULL, 'Francia', 'FR', 48.8566, 2.3522);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Podgorica', 'Podgorica', NULL, 'Montenegro', 'ME', 42.4304, 19.2594);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Praga', 'Praga', NULL, 'Repubblica Ceca', 'CZ', 50.0755, 14.4378);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Reykjavik', 'Reykjavik', NULL, 'Islanda', 'IS', 64.1265, -21.8174);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Riga', 'Riga', NULL, 'Lettonia', 'LV', 56.9496, 24.1052);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Roma', 'Roma', NULL, 'Italia', 'IT', 41.9028, 12.4964);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'San Marino', 'San Marino', NULL, 'San Marino', 'SM', 43.9424, 12.4578);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Sarajevo', 'Sarajevo', NULL, 'Bosnia-Erzegovina', 'BA', 43.8563, 18.4131);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Skopje', 'Skopje', NULL, 'Macedonia del Nord', 'MK', 41.9981, 21.4254);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Sofia', 'Sofia', NULL, 'Bulgaria', 'BG', 42.6977, 23.3219);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Stoccolma', 'Stoccolma', NULL, 'Svezia', 'SE', 59.3293, 18.0686);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Tallinn', 'Tallinn', NULL, 'Estonia', 'EE', 59.437, 24.7536);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Tirana', 'Tirana', NULL, 'Albania', 'AL', 41.3275, 19.8187);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Vaduz', 'Vaduz', NULL, 'Liechtenstein', 'LI', 47.141, 9.5215);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Valletta', 'Valletta', NULL, 'Malta', 'MT', 35.8997, 14.5147);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Varsavia', 'Varsavia', NULL, 'Polonia', 'PL', 52.2297, 21.0122);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Vienna', 'Vienna', NULL, 'Austria', 'AT', 48.2082, 16.3738);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Vilnius', 'Vilnius', NULL, 'Lituania', 'LT', 54.6872, 25.2797);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_eu', 'Zagabria', 'Zagabria', NULL, 'Croazia', 'HR', 45.815, 15.9819);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Abidjan', 'Abidjan', 'Africa', 'Costa d''Avorio', 'CI', 5.36, -4.0083);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Abuja', 'Abuja', 'Africa', 'Nigeria', 'NG', 9.0765, 7.3986);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Accra', 'Accra', 'Africa', 'Ghana', 'GH', 5.6037, -0.187);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Addis Abeba', 'Addis Abeba', 'Africa', 'Etiopia', 'ET', 9.032, 38.7469);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Algeri', 'Algeri', 'Africa', 'Algeria', 'DZ', 36.7372, 3.0865);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Antananarivo', 'Antananarivo', 'Africa', 'Madagascar', 'MG', -18.9137, 47.5361);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Asmara', 'Asmara', 'Africa', 'Eritrea', 'ER', 15.3229, 38.9251);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bamako', 'Bamako', 'Africa', 'Mali', 'ML', 12.6392, -8.0029);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bangui', 'Bangui', 'Africa', 'Rep. Centrafricana', 'CF', 4.3612, 18.555);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Banjul', 'Banjul', 'Africa', 'Gambia', 'GM', 13.4531, -16.5775);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bissau', 'Bissau', 'Africa', 'Guinea-Bissau', 'GW', 11.8636, -15.5977);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Brazzaville', 'Brazzaville', 'Africa', 'Rep. del Congo', 'CG', -4.2634, 15.2429);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bujumbura', 'Bujumbura', 'Africa', 'Burundi', 'BI', -3.3731, 29.3644);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Cairo', 'Cairo', 'Africa', 'Egitto', 'EG', 30.0444, 31.2357);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Città del Capo', 'Città del Capo', 'Africa', 'Sudafrica', 'ZA', -33.9249, 18.4241);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Conakry', 'Conakry', 'Africa', 'Guinea', 'GN', 9.537, -13.6773);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Cotonou', 'Cotonou', 'Africa', 'Benin', 'BJ', 6.3654, 2.3912);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Dakar', 'Dakar', 'Africa', 'Senegal', 'SN', 14.7167, -17.4677);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Djibouti', 'Djibouti', 'Africa', 'Gibuti', 'DJ', 11.5721, 43.1456);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Dodoma', 'Dodoma', 'Africa', 'Tanzania', 'TZ', -6.173, 35.7395);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Freetown', 'Freetown', 'Africa', 'Sierra Leone', 'SL', 8.4897, -13.2344);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Gaborone', 'Gaborone', 'Africa', 'Botswana', 'BW', -24.6282, 25.9231);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Harare', 'Harare', 'Africa', 'Zimbabwe', 'ZW', -17.8252, 31.0335);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Juba', 'Juba', 'Africa', 'Sudan del Sud', 'SS', 4.8594, 31.5713);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kampala', 'Kampala', 'Africa', 'Uganda', 'UG', 0.3476, 32.5825);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Khartoum', 'Khartoum', 'Africa', 'Sudan', 'SD', 15.5007, 32.5599);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kigali', 'Kigali', 'Africa', 'Ruanda', 'RW', -1.9441, 30.0619);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kinshasa', 'Kinshasa', 'Africa', 'Rep. Dem. Congo', 'CD', -4.3217, 15.3222);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Lagos', 'Lagos', 'Africa', 'Nigeria', 'NG', 6.5244, 3.3792);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Libreville', 'Libreville', 'Africa', 'Gabon', 'GA', 0.4162, 9.4673);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Lilongwe', 'Lilongwe', 'Africa', 'Malawi', 'MW', -13.9669, 33.7873);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Lomé', 'Lomé', 'Africa', 'Togo', 'TG', 6.1228, 1.2255);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Luanda', 'Luanda', 'Africa', 'Angola', 'AO', -8.8368, 13.2343);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Lusaka', 'Lusaka', 'Africa', 'Zambia', 'ZM', -15.4167, 28.2833);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Malabo', 'Malabo', 'Africa', 'Guinea Equatoriale', 'GQ', 3.7523, 8.7741);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Maputo', 'Maputo', 'Africa', 'Mozambico', 'MZ', -25.9692, 32.5732);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Maseru', 'Maseru', 'Africa', 'Lesotho', 'LS', -29.3167, 27.4833);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Mbabane', 'Mbabane', 'Africa', 'Eswatini', 'SZ', -26.3167, 31.1333);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Mogadiscio', 'Mogadiscio', 'Africa', 'Somalia', 'SO', 2.0469, 45.3182);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Monrovia', 'Monrovia', 'Africa', 'Liberia', 'LR', 6.3106, -10.8047);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Moroni', 'Moroni', 'Africa', 'Comore', 'KM', -11.7022, 43.2551);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Nairobi', 'Nairobi', 'Africa', 'Kenya', 'KE', -1.2921, 36.8219);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Ndjamena', 'Ndjamena', 'Africa', 'Ciad', 'TD', 12.1048, 15.0445);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Niamey', 'Niamey', 'Africa', 'Niger', 'NE', 13.5137, 2.1098);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Nouakchott', 'Nouakchott', 'Africa', 'Mauritania', 'MR', 18.0735, -15.9582);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Ouagadougou', 'Ouagadougou', 'Africa', 'Burkina Faso', 'BF', 12.3714, -1.5197);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Porto-Novo', 'Porto-Novo', 'Africa', 'Benin', 'BJ', 6.3703, 2.3912);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Praia', 'Praia', 'Africa', 'Capo Verde', 'CV', 14.9305, -23.5133);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Pretoria', 'Pretoria', 'Africa', 'Sudafrica', 'ZA', -25.7479, 28.2293);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Rabat', 'Rabat', 'Africa', 'Marocco', 'MA', 34.0132, -6.8326);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'São Tomé', 'São Tomé', 'Africa', 'São Tomé e Príncipe', 'ST', 0.3365, 6.7273);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Tripoli', 'Tripoli', 'Africa', 'Libia', 'LY', 32.8872, 13.1913);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Tunisi', 'Tunisi', 'Africa', 'Tunisia', 'TN', 36.819, 10.1658);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Windhoek', 'Windhoek', 'Africa', 'Namibia', 'NA', -22.5597, 17.0832);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Yamoussoukro', 'Yamoussoukro', 'Africa', 'Costa d''Avorio', 'CI', 6.8206, -5.2767);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Yaoundé', 'Yaoundé', 'Africa', 'Camerun', 'CM', 3.848, 11.5021);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Asunción', 'Asunción', 'Americhe', 'Paraguay', 'PY', -25.2867, -57.647);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bogotà', 'Bogotà', 'Americhe', 'Colombia', 'CO', 4.711, -74.0721);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Brasilia', 'Brasilia', 'Americhe', 'Brasile', 'BR', -15.8267, -47.9218);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Buenos Aires', 'Buenos Aires', 'Americhe', 'Argentina', 'AR', -34.6037, -58.3816);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Caracas', 'Caracas', 'Americhe', 'Venezuela', 'VE', 10.4806, -66.9036);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Cayenna', 'Cayenna', 'Americhe', 'Guyana Francese', 'GF', 4.9224, -52.3135);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Georgetown', 'Georgetown', 'Americhe', 'Guyana', 'GY', 6.8013, -58.1551);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Guatemala City', 'Guatemala City', 'Americhe', 'Guatemala', 'GT', 14.6349, -90.5069);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'L''Avana', 'L''Avana', 'Americhe', 'Cuba', 'CU', 23.1136, -82.3666);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'La Paz', 'La Paz', 'Americhe', 'Bolivia', 'BO', -16.5, -68.15);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Lima', 'Lima', 'Americhe', 'Perù', 'PE', -12.0464, -77.0428);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Managua', 'Managua', 'Americhe', 'Nicaragua', 'NI', 12.1149, -86.2362);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Mexico City', 'Mexico City', 'Americhe', 'Messico', 'MX', 19.4326, -99.1332);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Montevideo', 'Montevideo', 'Americhe', 'Uruguay', 'UY', -34.9011, -56.1645);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Nassau', 'Nassau', 'Americhe', 'Bahamas', 'BS', 25.048, -77.3554);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Ottawa', 'Ottawa', 'Americhe', 'Canada', 'CA', 45.4215, -75.6972);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Panama City', 'Panama City', 'Americhe', 'Panama', 'PA', 8.9936, -79.5197);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Paramaribo', 'Paramaribo', 'Americhe', 'Suriname', 'SR', 5.8664, -55.1668);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Port-au-Prince', 'Port-au-Prince', 'Americhe', 'Haiti', 'HT', 18.5944, -72.3074);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Port of Spain', 'Port of Spain', 'Americhe', 'Trinidad e Tobago', 'TT', 10.6596, -61.5189);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Quito', 'Quito', 'Americhe', 'Ecuador', 'EC', -0.1807, -78.4678);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'San José', 'San José', 'Americhe', 'Costa Rica', 'CR', 9.9281, -84.0907);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'San Salvador', 'San Salvador', 'Americhe', 'El Salvador', 'SV', 13.6929, -89.2182);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Santiago', 'Santiago', 'Americhe', 'Cile', 'CL', -33.4489, -70.6693);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Santo Domingo', 'Santo Domingo', 'Americhe', 'Rep. Dominicana', 'DO', 18.4861, -69.9312);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Tegucigalpa', 'Tegucigalpa', 'Americhe', 'Honduras', 'HN', 14.0723, -87.2062);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Washington D.C.', 'Washington D.C.', 'Americhe', 'USA', 'US', 38.9072, -77.0369);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Abu Dhabi', 'Abu Dhabi', 'Asia', 'Emirati Arabi', 'AE', 24.4539, 54.3773);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Amman', 'Amman', 'Asia', 'Giordania', 'JO', 31.9454, 35.9284);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Ankara', 'Ankara', 'Asia', 'Turchia', 'TR', 39.9334, 32.8597);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Astana', 'Astana', 'Asia', 'Kazakhstan', 'KZ', 51.1801, 71.446);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Baghdad', 'Baghdad', 'Asia', 'Iraq', 'IQ', 33.3152, 44.3661);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Baku', 'Baku', 'Asia', 'Azerbaigian', 'AZ', 40.4093, 49.8671);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bangkok', 'Bangkok', 'Asia', 'Thailandia', 'TH', 13.7563, 100.5018);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Beirut', 'Beirut', 'Asia', 'Libano', 'LB', 33.8938, 35.5018);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Bishkek', 'Bishkek', 'Asia', 'Kirghizistan', 'KG', 42.8746, 74.5698);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Colombo', 'Colombo', 'Asia', 'Sri Lanka', 'LK', 6.9271, 79.8612);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Damasco', 'Damasco', 'Asia', 'Siria', 'SY', 33.5138, 36.2765);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Dhaka', 'Dhaka', 'Asia', 'Bangladesh', 'BD', 23.8103, 90.4125);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Dili', 'Dili', 'Asia', 'Timor Est', 'TL', -8.5569, 125.5603);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Doha', 'Doha', 'Asia', 'Qatar', 'QA', 25.2854, 51.531);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Dubai', 'Dubai', 'Asia', 'Emirati Arabi', 'AE', 25.2048, 55.2708);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Dushanbe', 'Dushanbe', 'Asia', 'Tagikistan', 'TJ', 38.5598, 68.787);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Hanoi', 'Hanoi', 'Asia', 'Vietnam', 'VN', 21.0278, 105.8342);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Islamabad', 'Islamabad', 'Asia', 'Pakistan', 'PK', 33.6844, 73.0479);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Jakarta', 'Jakarta', 'Asia', 'Indonesia', 'ID', -6.2088, 106.8456);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kabul', 'Kabul', 'Asia', 'Afghanistan', 'AF', 34.5553, 69.2075);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kathmandu', 'Kathmandu', 'Asia', 'Nepal', 'NP', 27.7172, 85.324);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kuala Lumpur', 'Kuala Lumpur', 'Asia', 'Malaysia', 'MY', 3.139, 101.6869);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Kuwait City', 'Kuwait City', 'Asia', 'Kuwait', 'KW', 29.3759, 47.9774);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Manila', 'Manila', 'Asia', 'Filippine', 'PH', 14.5995, 120.9842);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Manama', 'Manama', 'Asia', 'Bahrein', 'BH', 26.2154, 50.5832);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Muscat', 'Muscat', 'Asia', 'Oman', 'OM', 23.588, 58.3829);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Naypyidaw', 'Naypyidaw', 'Asia', 'Myanmar', 'MM', 19.7633, 96.0785);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'New Delhi', 'New Delhi', 'Asia', 'India', 'IN', 28.6139, 77.209);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Pechino', 'Pechino', 'Asia', 'Cina', 'CN', 39.9042, 116.4074);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Phnom Penh', 'Phnom Penh', 'Asia', 'Cambogia', 'KH', 11.5564, 104.9282);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Pyongyang', 'Pyongyang', 'Asia', 'Corea del Nord', 'KP', 39.0392, 125.7625);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Riyadh', 'Riyadh', 'Asia', 'Arabia Saudita', 'SA', 24.7136, 46.6753);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Seoul', 'Seoul', 'Asia', 'Corea del Sud', 'KR', 37.5665, 126.978);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Singapore', 'Singapore', 'Asia', 'Singapore', 'SG', 1.3521, 103.8198);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Taipei', 'Taipei', 'Asia', 'Taiwan', 'TW', 25.033, 121.5654);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Taskent', 'Taskent', 'Asia', 'Uzbekistan', 'UZ', 41.2995, 69.2401);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Tehran', 'Tehran', 'Asia', 'Iran', 'IR', 35.6892, 51.389);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Thimphu', 'Thimphu', 'Asia', 'Bhutan', 'BT', 27.4728, 89.639);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Tokyo', 'Tokyo', 'Asia', 'Giappone', 'JP', 35.6762, 139.6503);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Ulan Bator', 'Ulan Bator', 'Asia', 'Mongolia', 'MN', 47.8864, 106.9057);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Vientiane', 'Vientiane', 'Asia', 'Laos', 'LA', 17.9757, 102.6331);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Yangon', 'Yangon', 'Asia', 'Myanmar', 'MM', 16.8409, 96.1735);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Yerevan', 'Yerevan', 'Asia', 'Armenia', 'AM', 40.1811, 44.5136);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Apia', 'Apia', 'Oceania', 'Samoa', 'WS', -13.8506, -171.7514);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Canberra', 'Canberra', 'Oceania', 'Australia', 'AU', -35.2809, 149.13);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Funafuti', 'Funafuti', 'Oceania', 'Tuvalu', 'TV', -8.5211, 179.1983);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Honiara', 'Honiara', 'Oceania', 'Isole Salomone', 'SB', -9.4333, 160.0333);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Majuro', 'Majuro', 'Oceania', 'Isole Marshall', 'MH', 7.1164, 171.1858);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Nuku''alofa', 'Nuku''alofa', 'Oceania', 'Tonga', 'TO', -21.1393, -175.2049);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Palikir', 'Palikir', 'Oceania', 'Micronesia', 'FM', 6.9248, 158.161);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Port Moresby', 'Port Moresby', 'Oceania', 'Papua Nuova Guinea', 'PG', -9.4438, 147.1803);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Port Vila', 'Port Vila', 'Oceania', 'Vanuatu', 'VU', -17.7333, 168.3167);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'South Tarawa', 'South Tarawa', 'Oceania', 'Kiribati', 'KI', 1.3278, 172.9756);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Suva', 'Suva', 'Oceania', 'Fiji', 'FJ', -18.1416, 178.4419);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Wellington', 'Wellington', 'Oceania', 'Nuova Zelanda', 'NZ', -41.2866, 174.7756);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Gerusalemme', 'Gerusalemme', 'Asia', 'Israele', 'IL', 31.7683, 35.2137);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Tel Aviv', 'Tel Aviv', 'Asia', 'Israele', 'IL', 32.0853, 34.7818);
INSERT INTO wandex_catalogo (categoria, chiave, nome, gruppo, paese, iso, lat, lng) VALUES ('capitali_mondo', 'Nicosia', 'Nicosia', 'Asia', 'Cipro', 'CY', 35.1856, 33.3823);