INSERT INTO viaggi (id, titolo, stato, data_inizio, data_fine, descrizione, note) VALUES (1, 'Cina & Hong Kong', 'futuro', '2026-08-21', '2026-09-08', '18 giorni, tutto su rotaia. Nessun volo interno.', '**Voli**
- Andata: 21 ago MXP → BRU (SN3154) → PEK (HU0492) · PNR ZI8TCU · arrivo 22 ago 05:00
- Ritorno: 7 set HKG → HAN (VN0593 14:30) · scalo 9h15 · HAN → MXP (VN0073 00:50) · PNR XLGNLT

**App essenziali da installare prima di partire**
WeChat · Alipay · Didi · Trip.com · VPN

**Treni**
Tutti prenotabili su Trip.com con passaporto');
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (101, 1, 'Pechino', 'Cina', 'CN', 39.9163, 116.3972, 1, 3, '2026-08-22', '2026-08-25', '{"nome":"Jingman Siheyuan Hotel","indirizzo":"Beijing Jishuitan Hospital Houhai Branch","link":"https://maps.google.com/?q=Jingman+Siheyuan+Hotel+Beijing+Houhai","prenotazione":"1381034208447234","costo":"126.81 EUR"}', '{"nome":"Pechino Nord","note":"Partenza 25 ago ore 07:30"}', 'Arrivo volo HU0492 ore 05:00 T2. Jet lag 6h — previsto riposo mattina.', 'Volo HU0492 BRU → PEK · arrivo 22 ago 05:00', 'AV Pechino Nord → Datong Sud · 07:30 · 25 agosto');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (1, 101, 1, 'Arrivo e orientamento', '2026-08-22');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (1, 1, '05:00', 'Arrivo Pechino T2', 'Bagagli, yuan, SIM cinese.', '', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (2, 1, '09:00', 'Riposo', '3-4h — jet lag di 6 ore.', '', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (3, 1, '14:00', 'Tempio dei Lama Yonghe', 'Il tempio lamaista più importante di Pechino.', 'attrazione', 39.9469, 116.4103);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (4, 1, '16:00', 'Torri del Tamburo e della Campana', '', 'attrazione', 39.9387, 116.3953);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (5, 1, '18:00', 'Hutong Nanluoguxiang', '', 'attrazione', 39.9369, 116.4011);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (6, 1, '19:30', 'Cena a Lago Houhai', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (2, 101, 2, 'Asse imperiale', '2026-08-23');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (7, 2, '07:30', 'Piazza Tiananmen', '', 'attrazione', 39.9055, 116.3976);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (8, 2, '09:00', 'Città Proibita', '3-4h.', 'attrazione', 39.9163, 116.3972);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (9, 2, '13:00', 'Parco Jingshan', 'Vista sulla Città Proibita.', 'attrazione', 39.9219, 116.3887);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (10, 2, '15:30', 'Tempio del Cielo', '~2h.', 'attrazione', 39.8822, 116.4066);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (11, 2, '18:30', 'Sera a Lago Houhai', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (3, 101, 3, 'Grande Muraglia', '2026-08-24');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (12, 3, '07:00', 'Partenza per Mutianyu', '~1h30.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (13, 3, '08:30', 'Grande Muraglia di Mutianyu', 'Funivia inclusa.', 'attrazione', 40.4319, 116.5636);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (14, 3, '11:00', 'Toboggan sulla Muraglia', '~15 min.', 'attrazione', 40.4319, 116.5636);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (15, 3, '13:30', 'Rientro a Pechino', '', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (16, 3, '15:30', 'Pomeriggio libero', '', '', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (17, 3, '20:00', 'Preparativi', 'Treno domani 07:30 da Pechino Nord.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (102, 1, 'Datong', 'Cina', 'CN', 40.0767, 113.2945, 2, 1, '2026-08-25', '2026-08-26', '{"nome":"Yungang Jianguo Hotel","indirizzo":"Datong, Cina","link":"https://maps.google.com/?q=Yungang+Jianguo+Hotel+Datong","prenotazione":"1381034496021784","costo":"43.75 EUR"}', '{"nome":"Datong Sud","note":"Arrivo 25 ago · partenza 26 ago 06:58"}', 'Giornata con taxi privato ~350 yuan.', 'AV Pechino Nord → Datong Sud · 07:30 · 25 agosto', 'AV Datong Sud → Xi''an · 06:58 · 26 agosto');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (4, 102, 1, 'Giornata con taxi privato', '2026-08-25');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (18, 4, '09:15', 'Arrivo Datong Sud', '~350 yuan taxi privato.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (19, 4, '10:00', 'Tempio Sospeso Xuankong Si', '~1h30 trasferimento. Visita ~1h30.', 'attrazione', 39.6608, 113.7272);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (20, 4, '14:30', 'Grotte di Yungang UNESCO', '~2h trasferimento. Visita 2h30-3h.', 'attrazione', 40.1102, 113.1285);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (21, 4, '17:30', 'Rientro a Datong', '', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (22, 4, '19:30', 'Cena: dao xiao mian', '', 'cibo', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (103, 1, 'Xi''an', 'Cina', 'CN', 34.2604, 108.9486, 3, 2, '2026-08-26', '2026-08-28', '{"nome":"KAJU Hotel","indirizzo":"","link":""}', '{"nome":"Xi''an North Station","note":"Partenza 28 ago sera"}', '', 'AV Datong Sud → Xi''an · 06:58 · 26 agosto', 'AV Xi''an → Changsha · sera 28 agosto · ~5h');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (5, 103, 1, 'Arrivo e città antica', '2026-08-26');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (23, 5, '11:30', 'Arrivo da Datong', 'AV ~4h30.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (24, 5, '13:30', 'Quartiere Musulmano', 'Street food: roujiamo, biang biang noodles.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (25, 5, '16:00', 'Torre della Campana e Torre del Tamburo', '', 'attrazione', 34.2665, 108.9479);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (26, 5, '19:30', 'Cena', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (6, 103, 2, 'Terracotta e mura', '2026-08-27');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (27, 6, '07:30', 'Partenza per Terracotta', 'Bus turistico n.5.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (28, 6, '09:00', 'Esercito di Terracotta', '3 fosse. ~3h.', 'attrazione', 34.3841, 109.2785);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (29, 6, '15:00', 'Mura della città in bici', '~1h30 giro completo.', 'attrazione', 34.2658, 108.9542);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (30, 6, '19:00', 'Cena e riposo', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (7, 103, 3, 'Giornata libera e partenza', '2026-08-28');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (31, 7, '09:00', 'Grande Moschea di Xi''an', 'Una delle più antiche d''Asia. ~1h.', 'attrazione', 34.2659, 108.9426);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (32, 7, '11:00', 'Museo di Storia dello Shaanxi', 'Collezione Tang straordinaria. ~2h. Gratuito.', 'attrazione', 34.2197, 108.9643);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (33, 7, '14:00', 'Pomeriggio libero', 'Shopping Huimin Street.', '', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (34, 7, '17:00', 'Partenza per Changsha', 'AV ~5h.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (104, 1, 'Changsha', 'Cina', 'CN', 28.1987, 112.9724, 4, 1, '2026-08-28', '2026-08-29', '{"nome":"KAJU Hotel","indirizzo":"Xi''an Bell and Drum Tower, Huimin Street","link":"https://maps.google.com/?q=KAJU+Hotel+Xian+Bell+Drum+Tower","prenotazione":"1381034496045509","costo":"28.82 EUR"}', '{"nome":"Changsha South Station","note":"Arrivo sera 28 · partenza mattina 29"}', '', 'AV Xi''an → Changsha · ~5h · sera 28 agosto', 'AV Changsha South → Zhangjiajie West · ~2h · mattina 29 agosto');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (8, 104, 1, 'Tappa di transito', '2026-08-28');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (35, 8, '22:00', 'Arrivo da Xi''an', 'Check-in hotel vicino alla stazione.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (36, 8, '22:30', 'Taiping Road Street Food', 'Cucina Hunan piccantissima. Tang hulu, smelly tofu fritto.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (37, 8, '08:00', 'Museo Provinciale Hunan (facoltativo)', 'La mummia di Lady Dai (200 a.C.). ~1h30.', 'attrazione', 28.1942, 112.9836);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (38, 8, '10:00', 'Monte Yuelu', 'Accademia millenaria. ~1h.', 'attrazione', 28.1877, 112.9304);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (39, 8, '12:00', 'Pranzo + partenza', 'AV Changsha South → Zhangjiajie West. ~2h.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (105, 1, 'Zhangjiajie', 'Cina', 'CN', 29.1256, 110.4785, 5, 2, '2026-08-29', '2026-08-31', '{"nome":"Thousand Hotel","indirizzo":"","link":""}', '{"nome":"Zhangjiajie West","note":""}', '', 'AV Changsha → Zhangjiajie West · ~2h · 29 agosto', 'AV Zhangjiajie → Fenghuanggucheng · poi taxi 10 km · 31 agosto');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (9, 105, 1, 'Tianmen Mountain', '2026-08-29');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (40, 9, 'Pomeriggio', 'Arrivo da Changsha', 'AV ~2h. Check-in Thousand Hotel.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (41, 9, '15:00', 'Funivia Tianmen Mountain', '7.455m, 30 min. ~258 yuan.', 'attrazione', 29.0469, 110.4725);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (42, 9, '16:30', 'Porta del Paradiso + passerelle vetro', '', 'attrazione', 29.0758, 110.4808);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (43, 9, '18:00', 'Discesa · cena', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (10, 105, 2, 'Avatar Mountains · Wulingyuan', '2026-08-30');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (44, 10, '06:30', 'Ingresso parco Wulingyuan', '', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (45, 10, '07:00', 'Ascensore Bailong', '335m in 88 sec.', 'attrazione', 29.3177, 110.4358);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (46, 10, '08:00', 'Yuanjiajie · Avatar Mountain', 'Southern Sky Column.', 'attrazione', 29.3522, 110.4364);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (47, 10, '11:00', 'Monte Tianzi', 'Bus navetta gratuito.', 'attrazione', 29.3817, 110.4217);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (48, 10, '14:30', 'Golden Whip Stream', '7.5 km. Scimmie selvatiche.', 'attrazione', 29.3213, 110.4536);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (49, 10, '17:00', 'Uscita · cena', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (11, 105, 3, 'Partenza per Fenghuang', '2026-08-31');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (50, 11, 'Mattina', 'Treno per Fenghuanggucheng', 'AV ~1h. Poi taxi 10 km / ~25 yuan.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (106, 1, 'Fenghuang', 'Cina', 'CN', 27.9505, 109.5989, 6, 1, '2026-08-31', '2026-09-01', '{"nome":"Anzhidinglan B&B","indirizzo":"Sul fiume Tuojiang","note":"Pickup dalla stazione incluso."}', '{"nome":"Fenghuanggucheng","note":"~10 km dalla città antica"}', '', 'AV Zhangjiajie → Fenghuanggucheng ~1h · 31 agosto', 'Treno Fenghuanggucheng → Guilin · ~3-4h · 1 settembre');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (12, 106, 1, 'Città della fenice', '2026-08-31');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (51, 12, '12:00', 'Arrivo da Zhangjiajie', 'AV ~1h, poi taxi ~25 yuan.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (52, 12, '13:00', 'Check-in Anzhidinglan B&B', 'Sul fiume Tuojiang. Pickup incluso.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (53, 12, '14:00', 'Ponte Arcobaleno + Diaojiaolou', '', 'attrazione', 27.9172, 109.6736);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (54, 12, '16:30', 'Barca sul Tuojiang', '~30-40 yuan.', 'attrazione', 27.9153, 109.6742);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (55, 12, '18:30', 'Cena con sapori Miao', 'Anatra al sangue, pesce piccante.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (56, 12, '19:30', 'Crociera serale illuminata', '', 'attrazione', 27.9153, 109.6742);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (57, 12, '20:30', 'Falò Miao (facoltativo)', '50–80 yuan.', 'attrazione', 27.9172, 109.6736);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (13, 106, 2, 'Alba e partenza', '2026-09-01');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (58, 13, '07:00', 'Passeggiata all''alba', 'Silenziosa e autentica.', 'attrazione', 24.7781, 110.4942);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (59, 13, '10:00', 'Taxi per la stazione', 'Navetta Anzhidinglan inclusa.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (107, 1, 'Guilin', 'Cina', 'CN', 25.2786, 110.295, 7, 2, '2026-09-01', '2026-09-03', '{"nome":"Shitsan Bliss Qintai Ethnic Boutique Hotel","indirizzo":"Changsha, Cina","link":"https://maps.google.com/?q=Shitsan+Bliss+Qintai+Ethnic+Boutique+Hotel+Changsha","prenotazione":"1381034496080884","costo":"57.26 EUR"}', '{"nome":"Guilin","note":""}', '', 'Treno Fenghuanggucheng → Guilin · ~3-4h · 1 settembre', 'Crociera Li River → Yangshuo · 3 settembre · poi → Hong Kong · 4 settembre');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (14, 107, 1, 'Arrivo e serata sul lago', '2026-09-01');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (60, 14, '15:00', 'Arrivo da Fenghuang', '', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (61, 14, '17:30', 'Pagode del Sole e della Luna', 'Al tramonto sul Lago Shanhu.', 'attrazione', 25.2744, 110.2936);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (62, 14, '19:00', 'Zhengyang Road', 'Ponti illuminati, cibo di strada.', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (15, 107, 2, 'Gita a Longji + Reed Flute Cave', '2026-09-02');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (63, 15, '07:30', 'Partenza auto privata per Longji', '~1h30. Biglietto 80 yuan.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (64, 15, '09:00', 'Jinkeng/Dazhai · Punti panoramici', 'Terrazze verde brillante. ~3h di cammino.', 'attrazione', 25.7794, 110.0697);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (65, 15, '13:00', 'Pranzo al villaggio', 'Riso glutinoso in canna di bambù, vino di riso Yao.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (66, 15, '14:30', 'Rientro a Guilin', '~1h30. Arrivo ~16:00.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (67, 15, '16:30', 'Reed Flute Cave', 'Grotta 180m con stalattiti illuminate. ~1h.', 'attrazione', 25.2403, 110.2497);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (68, 15, '19:00', 'Cena · preparativi crociera', '', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (16, 107, 3, 'Crociera Li River → Yangshuo', '2026-09-03');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (69, 16, '08:00', 'Transfer al molo Zhujiang', '~30 min da Guilin centro.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (70, 16, '09:30', 'Crociera Li River', '4h30. Karst, villaggi, bufali, pescatori con cormorani.', 'attrazione', 25.0638, 110.2972);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (71, 16, '14:00', 'Arrivo a Yangshuo', 'Molo Longtoushan. Taxi per hotel.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (108, 1, 'Yangshuo', 'Cina', 'CN', 24.777, 110.4953, 8, 1, '2026-09-03', '2026-09-04', '{"nome":"THOUSAND HOTEL","indirizzo":"Zhangjiajie, Cina","link":"https://maps.google.com/?q=THOUSAND+HOTEL+Zhangjiajie","prenotazione":"1381034605073838","costo":"71.58 EUR"}', '{"nome":"","note":""}', '', 'Crociera Li River → Yangshuo · 3 settembre', 'Yangshuo → Guilin → Guangzhou AV (~2h30) → MTR Hong Kong (~50 min) · 4 settembre');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (17, 108, 1, 'Arrivo dalla crociera', '2026-09-03');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (72, 17, '14:00', 'Sbarco a Yangshuo', 'Molo Longtoushan. Taxi per hotel.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (73, 17, '15:30', 'West Street', 'Architettura Ming-Qing, caffè, artigianato.', 'attrazione', 24.7781, 110.4942);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (74, 17, '17:00', 'Bici tra le colline carsiche', '', 'attrazione', 24.7781, 110.4942);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (75, 17, '20:00', 'Impression Sanjie Liu', '~200 yuan.', 'attrazione', 24.8897, 110.4342);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (18, 108, 2, 'Mattina e partenza per Hong Kong', '2026-09-04');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (76, 18, '07:30', 'Fiume Yulong in zattera', '~80 yuan, 1h.', 'attrazione', 24.7519, 110.4786);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (77, 18, '09:30', 'Check-out e partenza', '', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (78, 18, '10:30', 'Bus Yangshuo → Guilin', '~1h. Poi AV Guangzhou (~2h30).', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (79, 18, '15:00', 'MTR → Hong Kong', '~50 min. Arrivo West Kowloon.', 'logistica', NULL, NULL);
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (109, 1, 'Hong Kong', 'Hong Kong', 'HK', 22.2978, 114.1722, 9, 3, '2026-09-04', '2026-09-07', '{"nome":"","indirizzo":"Tsim Sha Tsui, Kowloon","link":""}', '{"nome":"West Kowloon","note":"Arrivo MTR da Guangzhou"}', 'Nessun visto per italiani · 90 giorni', 'MTR Cross-Boundary Guangzhou → West Kowloon · ~50 min · 4 settembre', 'Volo VN0593 HKG → HAN 14:30 · scalo 9h15 · VN0073 00:50 → MXP · PNR XLGNLT');
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (19, 109, 1, 'Arrivo e Kowloon', '2026-09-04');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (80, 19, '16:00', 'Arrivo West Kowloon', 'Da Guangzhou via MTR.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (81, 19, '17:30', 'Check-in hotel Kowloon', 'Tsim Sha Tsui.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (82, 19, '19:00', 'Temple Street Night Market', 'Cibo di strada, cartomanti, souvenir.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (83, 19, '21:00', 'Skyline Avenue of Stars', 'Il panorama notturno più bello di HK.', 'attrazione', 22.2949, 114.1722);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (20, 109, 2, 'Victoria Peak e isola', '2026-09-05');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (84, 20, '08:00', 'Dim sum del mattino', 'Ristoranti locali a Sham Shui Po.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (85, 20, '09:30', 'Star Ferry → HK Island', '3.5 HKD, 10 min.', 'attrazione', 22.2937, 114.1687);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (86, 20, '10:00', 'Peak Tram → Victoria Peak', '', 'attrazione', 22.2759, 114.1455);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (87, 20, '11:30', 'Central e SoHo', 'Hollywood Road. Escalator coperta.', 'attrazione', 22.2822, 114.1545);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (88, 20, '15:00', 'Mong Kok', 'Ladies Market e Flower Market.', 'attrazione', 22.3193, 114.1694);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (89, 20, '19:00', 'Cena cantonese', 'Rooftop bar con skyline.', 'cibo', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (21, 109, 3, 'Lantau Island', '2026-09-06');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (90, 21, '09:00', 'MTR → Tung Chung · Cable car Ngong Ping', '25 min di funivia panoramica.', 'logistica', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (91, 21, '10:30', 'Tian Tan Big Buddha', '34m. 268 scalini. Vista sull''oceano.', 'attrazione', 22.2538, 113.9053);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (92, 21, '12:30', 'Pranzo vegetariano monastero Po Lin', '', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (93, 21, '14:30', 'Villaggio Tai O', 'Il ''Venezia di Hong Kong''. Delfini rosa.', 'attrazione', 22.2527, 113.8618);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (94, 21, '17:30', 'Rientro a Kowloon', 'Ultima sera a Hong Kong.', 'logistica', NULL, NULL);
INSERT INTO giorni (id, tappa_id, numero, titolo, data) VALUES (22, 109, 4, 'Mattina libera e partenza', '2026-09-07');
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (95, 22, '08:00', 'Ultima colazione', 'Dim sum o cha chaan teng locale.', 'cibo', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (96, 22, '10:00', 'Passeggiata o shopping finale', '', '', NULL, NULL);
INSERT INTO attivita (id, giorno_id, ora, nome, note, tipo, lat, lng) VALUES (97, 22, '12:30', 'Airport Express da Hong Kong Station', '~24 min.', 'logistica', NULL, NULL);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Visto Cina (tipo L, ~60-80€)', 0, 0);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'VPN installata e testata', 0, 1);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'WeChat attivato', 0, 2);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Alipay attivato', 0, 3);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Assicurazione viaggio', 0, 4);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Città Proibita — biglietti WeChat', 0, 5);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Grande Muraglia Mutianyu — mutianyugreatwall.com', 0, 6);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Esercito di Terracotta — bmy.com.cn', 0, 7);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Grotte di Yungang — WeChat', 0, 8);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Crociera Li River — WeChat Lijiang Ticketing Office', 0, 9);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Cable car Ngong Ping Lantau — prenotare online', 0, 10);
INSERT INTO checklist_voci (viaggio_id, testo, completata, ordine) VALUES (1, 'Yuan cinesi e dollari HK', 0, 11);
INSERT INTO viaggi (id, titolo, stato, data_inizio, data_fine, descrizione, note) VALUES (2, 'Thailandia', 'passato', '2018-09-17', '2018-09-29', '12 giorni a Bangkok.', '');
INSERT INTO tappe (id, viaggio_id, nome, paese, paese_iso, lat, lng, ordine, notti, data_arrivo, data_partenza, hotel, stazione, note, trasporto_arrivo, trasporto_partenza) VALUES (201, 2, 'Bangkok', 'Thailandia', 'TH', 13.7563, 100.5018, 1, 12, '2018-09-17', '2018-09-29', '{"nome":"Anzhidinglan B&B","indirizzo":"Fenghuang Ancient Town, sul fiume Tuojiang","link":"https://maps.google.com/?q=Anzhidinglan+BB+Fenghuang+Ancient+Town","prenotazione":"1381034605100809","costo":"31.00 EUR"}', '{}', '', '', '');